"""Write gmail triage execution summaries to an Obsidian vault (Markdown)."""

from __future__ import annotations

import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from openclaw.skills.gmail_triage.models import TriageRunSummary

logger = logging.getLogger(__name__)


def _obsidian_filename_tag(account_email: str) -> str:
    """Return the trailing segment for run log filenames (``rba_fx`` uses ``obsidian_user``).

    If ``OBSIDIAN_USER`` is set in the environment, it is used (sanitized). Otherwise the
    local-part of ``account_email`` is used so filenames stay stable without extra config.
    """
    custom = (os.environ.get("OBSIDIAN_USER") or "").strip()
    if custom:
        tag = re.sub(r"[^a-zA-Z0-9_-]+", "_", custom)
        return tag or "user"
    local = account_email.split("@", 1)[0] if "@" in account_email else account_email
    tag = re.sub(r"[^a-zA-Z0-9_-]+", "_", local).strip("_")
    return tag or "local"


def write_summary(
    summary: TriageRunSummary,
    *,
    vault_path: str,
    log_subfolder: str,
) -> Path | None:
    """Write a Markdown run log under the Obsidian vault.

    Failures are logged and do not raise.

    Filename matches ``rba_fx`` convention:
    ``{YYYY-MM-DDTHH-MM-SSZ}_gmail_triage_{tag}.md`` (UTC timestamp prefix).

    Args:
        summary: Run outcome and metrics.
        vault_path: Absolute path to the Obsidian vault root.
        log_subfolder: Subfolder inside the vault (e.g. ``OpenClaw/Logs``).

    Returns:
        Path to the file written, or ``None`` if writing failed.
    """
    try:
        now_local = datetime.now().astimezone()
        now_utc = datetime.now(timezone.utc)
        file_run_id = (
            f"{now_utc:%Y-%m-%dT%H-%M-%SZ}_gmail_triage_{_obsidian_filename_tag(summary.account)}"
        )
        rel = Path(log_subfolder.strip("/").replace("\\", "/"))
        out_dir = Path(vault_path).expanduser() / rel
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{file_run_id}.md"

        status_md = "✅ Success" if summary.success else "❌ Failed"

        lines: list[str] = [
            f"# Gmail Triage — {now_local:%Y-%m-%d} {now_local:%H:%M:%S %Z}",
            "",
            f"**Account:** {summary.account}",
            f"**Run ID:** {summary.run_id}",
            f"**Status:** {status_md}",
            "",
            "## Summary",
            "",
            "| Metric | Count |",
            "|--------|-------|",
            f"| Emails scanned | {summary.emails_scanned} |",
            f"| Drafts created | {summary.drafts_created} |",
            f"| Flagged for deletion | {summary.flagged_for_deletion} |",
            "",
            "## Important Emails (Drafts Created)",
            "",
        ]
        if summary.important_entries:
            for e in summary.important_entries:
                lines.append(f"- **{e.subject}** — from {e.sender} at {e.received_at:%Y-%m-%d %H:%M}")
                lines.append(f"  - Reason: {e.reason}")
                lines.append("")
        else:
            lines.append("_None in this run._")
            lines.append("")

        lines.extend(
            [
                "## Flagged for Deletion",
                "",
            ],
        )
        if summary.deletable_entries:
            for e in summary.deletable_entries:
                lines.append(f"- **{e.subject}** — from {e.sender}")
                lines.append(f"  - Reason: {e.reason}")
                lines.append("")
        else:
            lines.append("_None in this run._")
            lines.append("")

        lines.extend(
            [
                "## Errors",
                "",
            ],
        )
        if summary.errors:
            for err in summary.errors:
                lines.append(f"- {err}")
        else:
            lines.append("None")

        lines.extend(
            [
                "",
                "---",
                "",
                "*Generated by OpenClaw gmail_triage skill*",
                "",
            ],
        )

        out_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Wrote Obsidian log %s", out_path)
        return out_path
    except Exception as exc:  # noqa: BLE001
        logger.warning("Obsidian log write failed: %s", exc)
        return None
