"""Write Bitcoin balance monitor run logs to an Obsidian vault (Markdown)."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from openclaw.skills.bitcoin_balance_monitor.models import MonitorRunSummary, WalletScanResult

logger = logging.getLogger(__name__)


def write_summary(
    summary: MonitorRunSummary,
    *,
    vault_path: str,
    log_subfolder: str,
) -> Path | None:
    """Write a Markdown run log under the Obsidian vault.

    Failures are logged and do not raise.

    Filename: ``{YYYY-MM-DDTHH-MM-SSZ}_bitcoin_balance_monitor.md`` (UTC timestamp prefix).
    """
    try:
        now_local = datetime.now().astimezone()
        now_utc = datetime.now(timezone.utc)
        file_run_id = f"{now_utc:%Y-%m-%dT%H-%M-%SZ}_bitcoin_balance_monitor"
        rel = Path(log_subfolder.strip("/").replace("\\", "/"))
        out_dir = Path(vault_path).expanduser() / rel
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{file_run_id}.md"

        status_md = "DEGRADED" if summary.degraded else ("OK" if summary.success else "FAILED")

        lines: list[str] = [
            f"# Bitcoin Balance Monitor — {now_local:%Y-%m-%d} {now_local:%H:%M:%S %Z}",
            "",
            f"**Status:** {status_md}",
            f"**Discord alerts sent:** {summary.discord_alerts_sent}",
            "",
            "## Wallets",
            "",
            "| Label | Confirmed (sats) | Unconfirmed (sats) | Total (sats) | Alert | Notes |",
            "|-------|------------------|--------------------|--------------|-------|-------|",
        ]

        for result in summary.wallet_results:
            if result.balance is not None:
                balance = result.balance
                notes: list[str] = []
                if result.is_first_run:
                    notes.append("baseline recorded")
                if result.alert_suppressed_dust:
                    notes.append("dust suppressed")
                if result.error:
                    notes.append(result.error)
                alert = "yes" if result.alert_sent else "no"
                lines.append(
                    f"| {result.label} | {balance.confirmed_sats:,} | "
                    f"{balance.unconfirmed_sats:,} | {balance.total_sats:,} | {alert} | "
                    f"{'; '.join(notes) if notes else '-'} |",
                )
            else:
                lines.append(
                    f"| {result.label} | - | - | - | no | {result.error or 'scan failed'} |",
                )

        lines.extend(
            [
                "",
                "## Errors",
                "",
            ],
        )
        if summary.errors:
            for err in summary.errors:
                lines.append(f"- {err}")
        else:
            lines.append("None")

        lines.extend(
            [
                "",
                "---",
                "",
                "*Generated by OpenClaw bitcoin_balance_monitor skill*",
                "",
            ],
        )

        out_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Wrote Obsidian log %s", out_path)
        return out_path
    except Exception as exc:  # noqa: BLE001
        logger.warning("Obsidian log write failed: %s", exc)
        return None
