"""Write RevenueCat metrics run logs to an Obsidian vault (Markdown)."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from openclaw.skills.revenuecat_metrics.revenuecat_client import MetricsSnapshot, utc_today

logger = logging.getLogger(__name__)


def format_daily_summary(snapshot: MetricsSnapshot) -> str:
    """Format a concise plain-text summary for Obsidian and Discord."""
    day = utc_today().isoformat()
    currency = snapshot.currency or "USD"
    lines = [
        f"RevenueCat daily metrics — {day} (UTC)",
        f"Active subscriptions: {snapshot.active_subscriptions:,}",
        f"Active trials: {snapshot.active_trials:,}",
        f"MRR: ${snapshot.mrr:,.2f} {currency}",
        f"Revenue (28d): ${snapshot.revenue_28d:,.2f} {currency}",
        f"New customers (28d): {snapshot.new_customers:,}",
        f"Active users (28d): {snapshot.active_users:,}",
        f"Snapshot: {snapshot.snapshot_at:%Y-%m-%d %H:%M:%S} UTC",
    ]
    return "\n".join(lines)


def write_summary(
    snapshot: MetricsSnapshot,
    *,
    vault_path: str,
    log_subfolder: str,
    success: bool = True,
    errors: list[str] | None = None,
) -> Path | None:
    """Write a Markdown run log under the Obsidian vault.

    Failures are logged and do not raise.

    Filename: ``{YYYY-MM-DDTHH-MM-SSZ}_revenuecat_metrics.md`` (UTC timestamp prefix).
    """
    try:
        now_local = datetime.now().astimezone()
        now_utc = datetime.now(timezone.utc)
        file_run_id = f"{now_utc:%Y-%m-%dT%H-%M-%SZ}_revenuecat_metrics"
        rel = Path(log_subfolder.strip("/").replace("\\", "/"))
        out_dir = Path(vault_path).expanduser() / rel
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{file_run_id}.md"

        status_md = "✅ Success" if success else "❌ Failed"
        currency = snapshot.currency or "USD"
        err_lines = errors or []

        lines: list[str] = [
            f"# RevenueCat Metrics — {now_local:%Y-%m-%d} {now_local:%H:%M:%S %Z}",
            "",
            f"**Status:** {status_md}",
            f"**Snapshot (UTC):** {snapshot.snapshot_at:%Y-%m-%d %H:%M:%S} UTC",
            "",
            "## Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Active subscriptions | {snapshot.active_subscriptions:,} |",
            f"| Active trials | {snapshot.active_trials:,} |",
            f"| MRR | ${snapshot.mrr:,.2f} {currency} |",
            f"| Revenue (28d) | ${snapshot.revenue_28d:,.2f} {currency} |",
            f"| New customers (28d) | {snapshot.new_customers:,} |",
            f"| Active users (28d) | {snapshot.active_users:,} |",
            "",
            "## Plain text",
            "",
            "```",
            format_daily_summary(snapshot),
            "```",
            "",
            "## Errors",
            "",
        ]
        if err_lines:
            for err in err_lines:
                lines.append(f"- {err}")
        else:
            lines.append("None")

        lines.extend(
            [
                "",
                "---",
                "",
                "*Generated by OpenClaw revenuecat_metrics skill*",
                "",
            ],
        )

        out_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Wrote Obsidian log %s", out_path)
        return out_path
    except Exception as exc:  # noqa: BLE001
        logger.warning("Obsidian log write failed: %s", exc)
        return None
